// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Game struct {
	ID            int64
	GameID        string
	GameInfo      string
	CreatedDtTm   string
	CreatedUserID string
}

type Gamestate struct {
	ID          int64
	UserID      string
	GameID      int64
	GameState   string
	CreatedDtTm string
}

type Ratelimit struct {
	ID             int64
	UserID         string
	CallsRemaining int64
	ResetDtTm      string
}
